#ifndef _ColorFrag_h_
#define _ColorFrag_h_


// Header generated from binary by WriteAsBinHeader()..
static const int ColorFragLength = 42;
static const unsigned int ColorFrag[ColorFragLength]={
	0x20205350,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000002,	0x00000002,	0x00000000,	0x00000000,	0x00000001,	0x00000000,
	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x0000000B,	0x00000000,	0x00000000,	0x00000000,
	0x00FA10E4,	0x00000000,	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,
	0x3F800000,	0x3F800000,	0x3F800000,	0x3F800000,	0x00000000,	0x0000000A,	0x00000009,	0x00000000,	0x00000000,	0x6E6F7246,
	0x6C6F4374,	0x0000726F,};

//checksum generated by simpleCheckSum()
static const unsigned int ColorFragCheckSum = 69;

static const char* ColorFragText = 
	"#ifdef GL_ES\n"
	"precision highp float;\n"
	"#endif\n"
	"\n"
	"varying vec4 FrontColor;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    gl_FragColor = FrontColor;\n"
	"}";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader ColorFragShader(ColorFragText, ColorFrag, ColorFragLength, ColorFragCheckSum);


#endif


#endif //_ColorFrag_h_
