#ifndef _TextureFrag_h_
#define _TextureFrag_h_


// Header generated from binary by WriteAsBinHeader()..
static const int TextureFragLength = 89;
static const unsigned int TextureFrag[TextureFragLength]={
	0x20205350,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000009,	0x00000003,	0x00000000,	0x00000000,	0x00000001,	0x00000000,
	0x00000001,	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x0000001D,	0x00000000,	0x18000000,	0x0718FF07,
	0x230820FF,	0x00000000,	0x08FF0708,	0x0718FF07,	0x0EF82105,	0x00000000,	0x02000000,	0x01014402,	0x037821E4,	0x00000000,
	0x00000000,	0x81010000,	0x114021E4,	0x00000000,	0x00000000,	0x01010001,	0x034021FF,	0x00000000,	0x00000000,	0x01010000,
	0x074021FF,	0x00000000,	0x00000000,	0x00000000,	0x00B821A4,	0x00000000,	0x00000000,	0x0101E407,	0x107A10E4,	0x00000000,
	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,
	0x3F800000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000013,	0x00000009,	0x00000009,	0x00000000,
	0x00000000,	0x00000000,	0x00000007,	0x00000003,	0x00020001,	0x00000008,	0x00000008,	0x0000000A,	0x0000000F,	0x00030005,
	0x00000000,	0x44786554,	0x00306D69,	0x49786554,	0x6567616D,	0x54003073,	0x6F437865,	0x3064726F,	0x00000000,};

//checksum generated by simpleCheckSum()
static const unsigned int TextureFragCheckSum = 106;

static const char* TextureFragText = 
	"#ifdef GL_ES\n"
	"precision highp float;\n"
	"#endif\n"
	"\n"
	"uniform sampler2D TexImages0;\n"
	"//uniform bool alphaTextureEnable[2]; \n"
	"//uniform bool noAlphaChannelTextureEnable[2]; \n"
	"\n"
	"varying vec4 TexCoord0;\n"
	"//varying vec4 FrontColor;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    vec4 srcColor;\n"
	"    \n"
	"    srcColor = texture2D(TexImages0, TexCoord0.xy);\n"
	"    \n"
	"//    if(alphaTextureEnable[0]) \n"
	"//    srcColor.rgb = FrontColor.rgb; \n"
	"//    else if(noAlphaChannelTextureEnable[0]) \n"
	"//    srcColor.a   = FrontColor.a; \n"
	"    \n"
	"    gl_FragColor = srcColor;\n"
	"}";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader TextureFragShader(TextureFragText, TextureFrag, TextureFragLength, TextureFragCheckSum);


#endif


#endif //_TextureFrag_h_
